[package]
name = "policy-cargo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
cargo_metadata.workspace = true
camino.workspace = true
globset.workspace = true
ignore.workspace = true
policy-core = { path = "../policy-core" }
thiserror.workspace = true

[lints]
workspace = true
